#!/usr/bin/env python3
"""bin2c.py - turn binary files into C arrays.

Usage:
  bin2c.py OUTPUT.c NAME=FILE [NAME=FILE ...]

Each FILE becomes "const UBYTE NAME[] = {...};" plus
"const ULONG NAME_size = <bytes>;". FILE paths are written to the
header comment as given.

Regenerate the about picture data (from the c directory):
  python3 tools/bin2c.py src/gui/aboutdata.c \
      about_scrollertxt=../src/abouttext.bin \
      about_picturebody=../src/bodyraw.bin \
      about_palette=../src/cmapraw.bin
"""
import os
import sys


def emit(out, name, data):
    out.write("const UBYTE %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        out.write("\t" + ", ".join("0x%02x" % b for b in chunk) + ",\n")
    out.write("};\n")
    out.write("const ULONG %s_size = %d;\n\n" % (name, len(data)))


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 1
    outname = argv[1]
    items = []
    for arg in argv[2:]:
        if "=" not in arg:
            sys.stderr.write("bad argument (want NAME=FILE): %s\n" % arg)
            return 1
        name, path = arg.split("=", 1)
        with open(path, "rb") as f:
            items.append((name, path, f.read()))
    with open(outname, "w", newline="\n") as out:
        out.write("/*\n * %s - binary data as C arrays, generated by"
                  " c/tools/bin2c.py; do not edit.\n *\n"
                  % os.path.basename(outname))
        for name, path, data in items:
            out.write(" *   %s: %s (%d bytes)\n" % (name, path, len(data)))
        out.write(" */\n#include <exec/types.h>\n\n")
        for name, path, data in items:
            emit(out, name, data)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
